apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "rancher.fullname" . }}
  labels:
{{ include "rancher.labels" . | indent 4 }}
spec:
  {{- /*
  If service.type is not provided this attribute is ommitted and k8s default of ClusterIP is used.
  */}} 
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: 80
    nodePort: {{ .Values.service.http.port }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.https.port }}
    targetPort: 444
    protocol: TCP
    nodePort: {{ .Values.service.https.port }}
    name: https-internal
  selector:
    app: {{ template "rancher.fullname" . }}
